// <auto-generated />
using System;
using Barter.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Barter.Infra.Data.Migrations
{
    [DbContext(typeof(BarterContext))]
    partial class BarterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Barter.Domain.Entities.Barter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnName("date");

                    b.Property<bool>("HasFinished")
                        .HasColumnName("finished");

                    b.Property<Guid>("ItemOfferedId")
                        .HasColumnName("item_offered_id");

                    b.Property<Guid>("ItemReceivedId")
                        .HasColumnName("item_received_id");

                    b.HasKey("Id");

                    b.ToTable("Barters");
                });
#pragma warning restore 612, 618
        }
    }
}
